name: ChangeLog generation
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  generate:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
          repository: "Govcraft/rust-docs-mcp-server"
      - run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v0.15.4/git-chglog_0.15.4_linux_amd64.tar.gz
          tar -xvzf git-chglog_0.15.4_linux_amd64.tar.gz
          ./git-chglog -o CHANGELOG.md
          rm git-chglog_0.15.4_linux_amd64.tar.gz
          rm git-chglog
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(docs): update CHANGELOG for latest tag"
          git push origin HEAD:$REF
        env:
          REF: "refs/deploy-bot/${{ github.run_id }}/merge"